# Generated by Django 5.1 on 2024-12-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmessage",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
